[BULK] - DocuTune remediation - Sensitive terms with GUIDs (part 5)
Azure/azure-docs-powershell-azuread pull request #1023
Opened 2024-10-18 18:59 UTC by meganbradley

Applying sensitive terms with GUID changes as part of Content SFI and outlined in [Overview - Writing content securely - Platform Manual](https://review.learn.microsoft.com/en-us/help/platform/security-reference?branch=main). Changes are part of the Microsoft-wide SFI effort. Point of contact: @CelesteDG

DocuTune v1.5.2.0
CorrelationId: [ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db](https://github.com/Azure/azure-docs-powershell-azuread/pulls?q=is%3Apr+ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db+)

#docutune

2024-10-22 09:37 UTC, msewaweru commented
Trigger rebuild.

2024-10-24 10:43 UTC, msewaweru approved these changes
Some GUIDs haven't been updated.

2024-10-24 10:43 UTC, msewaweru commented on azureadps-2.0-preview/AzureAD/Get-AzureADMSRoleAssignment.md
> +62e90394-69f5-4237-9190-012177145e34 aaaaaaaa-bbbb-cccc-1111-222222222222 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRqAVAnJQyBBLv1lM-1
Not all PrincipalId values have been updated.

2024-10-24 10:43 UTC, msewaweru commented on azureadps-2.0-preview/AzureAD/Get-AzureADMSRoleAssignment.yml
> +    62e90394-69f5-4237-9190-012177145e34 aaaaaaaa-bbbb-cccc-1111-222222222222 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRqAVAnJQyBBLv1lM-1
Not all PrincipalId values have been updated.

2024-10-24 10:45 UTC, msewaweru requested changes
Some GUIDs haven't been updated.

2024-12-05 14:47 UTC, cilwerner commented on azureadps-2.0-preview/AzureAD/Get-AzureADMSRoleAssignment.yml
> +    62e90394-69f5-4237-9190-012177145e34 aaaaaaaa-bbbb-cccc-1111-222222222222 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRtGDAnJQyBBLv1lM-1
```suggestion
    89c55b63-78c3-478b-b79e-074d0e87269e 69584002-b4d1-4055-9c94-320542efd653 /             Y1vFBcN4i0e3ngdNDocmngJAWGnRtGDAnJQyBBLv1lM-1
    62e90394-69f5-4237-9190-012177145e34 69584002-b4d1-4055-9c94-320542efd653 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRtGDAnJQyBBLv1lM-1
```

2024-12-05 14:50 UTC, cilwerner requested changes
@msewaweru, please commit and merge

2024-12-05 14:50 UTC, cilwerner commented on azureadps-2.0-preview/AzureAD/Get-AzureADMSRoleAssignment.yml
> +    62e90394-69f5-4237-9190-012177145e34 aaaaaaaa-bbbb-cccc-1111-222222222222 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRqAVAnJQyBBLv1lM-1
```suggestion
    62e90394-69f5-4237-9190-012177145e34 69584002-b4d1-4055-9c94-320542efd653 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRqAVAnJQyBBLv1lM-1
```

2024-12-05 14:50 UTC, cilwerner commented on azureadps-2.0-preview/AzureAD/Get-AzureADMSRoleAssignment.md
> +eb1d8c90-acf5-460d-8424-c1f1a6fbdb85 aaaaaaaa-bbbb-cccc-1111-222222222222 /             NIwd6_WsDUaEJMHxpvvbhQJAWGnRtGDAnJQyBBLv1lM-1
This shows up in the GUID list to be remediated, but will revert the table
```suggestion
89c55b63-78c3-478b-b79e-074d0e87269e 69584002-b4d1-4055-9c94-320542efd653 /             Y1vFBcN4i0e3ngdNDocmngJAWGnRtGDAnJQyBBLv1lM-1
62e90394-69f5-4237-9190-012177145e34 69584002-b4d1-4055-9c94-320542efd653 /             lAPpYvVpN0KRkAEhdxReEAJAWGnRtGDAnJQyBBLv1lM-1
eb1d8c90-acf5-460d-8424-c1f1a6fbdb85 69584002-b4d1-4055-9c94-320542efd653 /             NIwd6_WsDUaEJMHxpvvbhQJAWGnRtGDAnJQyBBLv1lM-1

```

2024-12-05 15:48 UTC, msewaweru approved these changes

2024-12-05 15:48 UTC, merged