[BULK] - DocuTune remediation - Sensitive terms with GUIDs (part 10)
Azure/azure-docs-powershell-azuread pull request #1028
Opened 2024-10-18 19:03 UTC by meganbradley

Applying sensitive terms with GUID changes as part of Content SFI and outlined in [Overview - Writing content securely - Platform Manual](https://review.learn.microsoft.com/en-us/help/platform/security-reference?branch=main). Changes are part of the Microsoft-wide SFI effort. Point of contact: @CelesteDG

DocuTune v1.5.2.0
CorrelationId: [ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db](https://github.com/Azure/azure-docs-powershell-azuread/pulls?q=is%3Apr+ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db+)

#docutune

2024-10-18 19:03 UTC, meganbradley commented
#docutune-review

2024-10-24 11:21 UTC, msewaweru approved these changes
LGTM!

2024-12-03 09:49 UTC, cilwerner approved these changes
@msewaweru, this looks good, can be merged.

2024-12-04 14:00 UTC, cilwerner requested changes
@msewaweru, only one revert needed here.

2024-12-04 14:00 UTC, cilwerner commented on azureadps-2.0-preview/AzureAD/Set-AzureADMSConditionalAccessPolicy.md
> +PS C:\> Set-AzureADMSConditionalAccessPolicy -PolicyId 1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5 -DisplayName "MFA policy 1" -State "Enabled"
```suggestion
PS C:\> Set-AzureADMSConditionalAccessPolicy -PolicyId 6b5e999b-0ba8-4186-a106-e0296c1c4358 -DisplayName "MFA policy 1" -State "Enabled"
```

2024-12-04 14:00 UTC, cilwerner commented on azureadps-2.0-preview/AzureAD/Set-AzureADMSConditionalAccessPolicy.md
> +          Id                      : 1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5
```suggestion
          Id                      : 6b5e999b-0ba8-4186-a106-e0296c1c4358
```

2024-12-04 17:36 UTC, msewaweru approved these changes
Good to go, @CelesteDG.

2024-12-05 14:51 UTC, merged