[BULK] - DocuTune remediation - Sensitive terms with GUIDs (part 18)
Azure/azure-docs-powershell-azuread pull request #1036
Opened 2024-10-18 19:11 UTC by meganbradley

Applying sensitive terms with GUID changes as part of Content SFI and outlined in [Overview - Writing content securely - Platform Manual](https://review.learn.microsoft.com/en-us/help/platform/security-reference?branch=main). Changes are part of the Microsoft-wide SFI effort. Point of contact: @CelesteDG

DocuTune v1.5.2.0
CorrelationId: [ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db](https://github.com/Azure/azure-docs-powershell-azuread/pulls?q=is%3Apr+ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db+)

#docutune

2024-10-18 19:11 UTC, meganbradley commented
#docutune-review

2024-12-03 11:53 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSApplicationKey.yml
> +    PS C:\>Remove-AzureADMSApplicationKey -ObjectId "aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb" -KeyId "FDA27CF-1B58-4CAE-8CE7-CD04F0AAB945" -Proof {token}
```suggestion
    PS C:\>Remove-AzureADMSApplicationKey -ObjectId "aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb" -KeyId "aaaaaaaa-0b0b-1c1c-2d2d-333333333333" -Proof {token}
```

2024-12-03 17:05 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.md
> +aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
rogue object id. 
```suggestion
79592454-dea7-4660-9d91-f1768e5055ac feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```

2024-12-03 17:05 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.md
> +PS C:\WINDOWS\system32> Remove-AzureADApplication -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb
Related to above, fixing in rerun
```suggestion
PS C:\WINDOWS\system32> Remove-AzureADApplication -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac
```

2024-12-03 17:06 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.md
> +aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```suggestion
79592454-dea7-4660-9d91-f1768e5055ac feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```

2024-12-03 17:06 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.md
> +PS C:\WINDOWS\system32> Restore-AzureADDeletedApplication -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb
```suggestion
PS C:\WINDOWS\system32> Restore-AzureADDeletedApplication -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac
```

2024-12-03 17:06 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.md
> +aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```suggestion
79592454-dea7-4660-9d91-f1768e5055ac feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```

2024-12-03 17:06 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.yml
> +    aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```suggestion
    79592454-dea7-4660-9d91-f1768e5055ac feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```

2024-12-03 17:07 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.yml
> +    PS C:\WINDOWS\system32> Restore-AzureADDeletedApplication -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb
```suggestion
    PS C:\WINDOWS\system32> Restore-AzureADDeletedApplication -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac
```

2024-12-03 17:07 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.yml
> +    aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```suggestion
    79592454-dea7-4660-9d91-f1768e5055ac feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```

2024-12-03 17:07 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.yml
> +    PS C:\WINDOWS\system32> Remove-AzureADApplication -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb
```suggestion
    PS C:\WINDOWS\system32> Remove-AzureADApplication -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac
```

2024-12-03 17:07 UTC, cilwerner commented on azureadps-2.0/AzureAD/Restore-AzureADDeletedApplication.yml
> +    aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```suggestion
    79592454-dea7-4660-9d91-f1768e5055ac feabcdd1-711a-4d55-ad5e-0d0577aaaa5e analog
```

2024-12-04 09:45 UTC, cilwerner requested changes
@msewaweru, I've double checked and seen that policy id is no longer a sensitive term. I remembered there being an issue in another repo about that.

2024-12-04 09:45 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSConditionalAccessPolicy.md
> +PS C:\> Remove-AzureADMSConditionalAccessPolicy -PolicyId 1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5
```suggestion
PS C:\> Remove-AzureADMSConditionalAccessPolicy -PolicyId 6b5e999b-0ba8-4186-a106-e0296c1c4358
```

2024-12-04 09:45 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSConditionalAccessPolicy.yml
> +    PS C:\> Remove-AzureADMSConditionalAccessPolicy -PolicyId 1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5
```suggestion
    PS C:\> Remove-AzureADMSConditionalAccessPolicy -PolicyId 6b5e999b-0ba8-4186-a106-e0296c1c4358
```

2024-12-04 09:45 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSNamedLocationPolicy.md
> +PS C:\> Remove-AzureADMSNamedLocationPolicy -PolicyId 1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5
```suggestion
PS C:\> Remove-AzureADMSNamedLocationPolicy -PolicyId 76fdfd4d-bd80-4c1e-8fd4-6abf49d121fe
```

2024-12-04 09:45 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSNamedLocationPolicy.yml
> +    PS C:\> Remove-AzureADMSNamedLocationPolicy -PolicyId 1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5
```suggestion
    PS C:\> Remove-AzureADMSNamedLocationPolicy -PolicyId 76fdfd4d-bd80-4c1e-8fd4-6abf49d121fe
```

2024-12-04 09:45 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSPermissionGrantConditionSet.md
> +PS C:\>Remove-AzureADMSPermissionGrantConditionSet -PolicyId "policy1" -ConditionSetType "excludes" -Id "1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5"
```suggestion
PS C:\>Remove-AzureADMSPermissionGrantConditionSet -PolicyId "policy1" -ConditionSetType "excludes" -Id "665a9903-0398-48ab-b4e9-7a570d468b66"
```

2024-12-04 09:45 UTC, cilwerner commented on azureadps-2.0/AzureAD/Remove-AzureADMSPermissionGrantConditionSet.yml
> +    PS C:\>Remove-AzureADMSPermissionGrantConditionSet -PolicyId "policy1" -ConditionSetType "excludes" -Id "1aaaaaa1-2bb2-3cc3-4dd4-5eeeeeeeeee5"
```suggestion
    PS C:\>Remove-AzureADMSPermissionGrantConditionSet -PolicyId "policy1" -ConditionSetType "excludes" -Id "665a9903-0398-48ab-b4e9-7a570d468b66"
```

2024-12-05 17:37 UTC, msewaweru approved these changes

2024-12-05 17:37 UTC, merged